/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 hero.gltf --transform 
Files: hero.gltf [2.77KB] > hero-transformed.glb [1.17KB] (58%)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/img/models/hero2-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.003']}
        position={[0, 0.115, 1.109]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[0.177, 1.887, 0.178]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['01-Search'].geometry}
        material={materials['Material.004']}
        position={[-1.142, 0.395, 1.195]}
        scale={6.011}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.black}
        position={[-1.125, 0.396, 0.966]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={2.582}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Solid_1001.geometry}
        material={materials['Material.001']}
        position={[0.058, 0.356, 0.47]}
        scale={[0.316, 0.122, 0.316]}
      />
      <instancedMesh
        args={[nodes.Plane002.geometry, materials.black, 13]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Plane002.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cylinder.geometry, materials.black, 6]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cylinder.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Cylinder006.geometry, materials['Material.003'], 9]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cylinder006.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload('/img/models/hero2-transformed.glb');
